version: "3.8"

services:
  sadtalker:
    image: sadtalker:latest
    build: ./
    container_name: deepfake_Sadtalker
    ipc: host
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]